In [6]:
import pandas as pd
import numpy
import matplotlib
from bs4 import BeautifulSoup
import requests

In [9]:
url = 'https://en.wikipedia.org/wiki/List_of_epidemics'

In [7]:
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

In [11]:
tables = pd.read_html(url)
tables

[                                                   0  \
 0  Plague panel with the triumph of death. 1607–3...
 1                                           Duration

                                                    1
 0  Plague panel with the triumph of death. 1607–3...
 1                                      Human history  ,
                             Death toll (estimate)  \
 0                                  75,000–100,000
 1                                    5–10 million
 2                                             NaN
 3                25–50 million; 40% of population
 4                                             NaN
 5                                       > 100,000
 6                                             NaN
 7                                             NaN
 8                                             NaN
 9   20–200 million; 20–60% of European population
 10                                       > 10,000

                                 Location                          Date  \
 0                                 Greece                    429–426 BC
 1                           Roman Empire  165–180 (possibly up to 190)
 2                                 Europe                       250–266
 3            Europe, Egypt and West Asia                       541–542
 4                                   Rome                           590
 5                      Ctesiphon, Persia                       627–628
 6                          British Isles                       664–689
 7                                  Japan                       735–737
 8    Byzantine Empire, West Asia, Africa                       746–747
 9          Europe, Asia and North Africa                     1331–1353
 10  England and later continental Europe                     1485–1551

                                      Event  \
 0                         Plague of Athens
 1                          Antonine Plague
 2                        Plague of Cyprian
 3                      Plague of Justinian
 4                      Roman Plague of 590
 5                         Plague of Sheroe
 6                            Plague of 664
 7       735–737 Japanese smallpox epidemic
 8                        Plague of 746–747
 9                              Black Death
 10  Sweating sickness (multiple outbreaks)

                                               Disease       Ref.
 0   Unknown, possibly typhus, typhoid fever or vir...  [1][2][3]
 1                          Unknown, possibly smallpox        [4]
 2                          Unknown, possibly smallpox        [5]
 3                                              Plague        [6]
 4                                              Plague        [7]
 5                                              Plague        [8]
 6                                              Plague        [9]
 7                                            Smallpox   [10][11]
 8                                              Plague       [12]
 9                                    Plague Y. pestis       [13]
 10  Unknown, possibly an unknown species of hantav...       [14]  ,
                     Death toll (estimate)  \
 0        5–15 million (80% of population)
 1                      > 20,100 in London
 2       2–2.5 million (50% of population)
 3                                     NaN
 4   > 19,900 in London and outer parishes
 5                                     NaN
 6                                     NaN
 7                                     NaN
 8                                     NaN
 9                    30–90% of population
 10                                 280000
 11                                    NaN
 12                                    NaN
 13                                    NaN
 14                                    NaN
 15                                    NaN
 16                                    NaN
 17                                    NaN
 18                                    NaN
 19                             24,148[32]
 20                            100,000[33]
 21                                  40000
 22                                    NaN
 23                                  76000
 24                                    NaN
 25                                    NaN

                                              Location       Date  \
 0                                              Mexico  1545–1548
 1                                              London  1563–1564
 2                                              Mexico  1576–1580
 3                                       Seneca nation  1592–1596
 4                                              London  1592–1593
 5                                               Spain  1596–1602
 6                                       South America  1600–1650
 7                                             England       1603
 8                                               Egypt       1609
 9   Southern New England, especially the Wampanoag...  1616–1619
 10                                              Italy  1629–1631
 11                                     Wyandot people       1634
 12                                  Thirteen Colonies       1633
 13                                            England       1636
 14                                              China  1641–1644
 15                                              Spain  1647–1652
 16                                    Central America       1648
 17                                              Italy       1656
 18                                  Thirteen Colonies       1657
 19                                        Netherlands  1663–1664
 20                                            England  1665–1666
 21                                             France       1668
 22                                              Spain  1676–1685
 23                                            Austria       1679
 24                                  Thirteen Colonies       1687
 25                                  Thirteen Colonies       1690

                                Event  \
 0   Cocoliztli Epidemic of 1545–1548
 1                 1563 London plague
 2        Cocoliztli epidemic of 1576
 3                                NaN
 4              1592–93 London plague
 5                                NaN
 6                                NaN
 7                                NaN
 8                                NaN
 9          1616 New England epidemic
 10       Italian plague of 1629–1631
 11                               NaN
 12   Massachusetts smallpox epidemic
 13                               NaN
 14                               NaN
 15           Great Plague of Seville
 16                               NaN
 17                     Naples Plague
 18                               NaN
 19                               NaN
 20            Great Plague of London
 21                               NaN
 22                               NaN
 23            Great Plague of Vienna
 24                               NaN
 25                               NaN

                                               Disease              Ref.
 0                        Possibly Salmonella enterica  [15][16][17][18]
 1                                              Plague               NaN
 2                        Possibly Salmonella enterica  [15][16][17][18]
 3                                             Measles              [19]
 4                                              Plague               NaN
 5                                              Plague              [20]
 6                                             Malaria              [21]
 7                                              Plague              [22]
 8                                              Plague               NaN
 9   Unknown cause. Latest research suggests epidem...          [23][24]
 10                                             Plague              [25]
 11                                           Smallpox              [26]
 12                                           Smallpox               NaN
 13                                             Plague              [27]
 14                                             Plague              [28]
 15                                             Plague               NaN
 16                                       Yellow fever              [29]
 17                                             Plague              [30]
 18                                            Measles              [31]
 19                                             Plague               NaN
 20                                             Plague              [34]
 21                                             Plague              [35]
 22                                             Plague              [36]
 23                                             Plague               NaN
 24                                            Measles              [37]
 25                                       Yellow fever               NaN  ,
            Death toll (estimate)                                     Location  \
 0                            NaN                           Canada, New France
 1   > 18,000 (36% of population)                                      Iceland
 2                            NaN                               Denmark,Sweden
 3                            NaN                            Thirteen Colonies
 4                            NaN                           Canada, New France
 5                            NaN                                       France
 6                            NaN                            Thirteen Colonies
 7                            NaN                            Thirteen Colonies
 8                            NaN                                        Spain
 9                            NaN                            Thirteen Colonies
 10                           NaN                           Canada, New France
 11                      > 50,000                                      Balkans
 12                           NaN                            Thirteen Colonies
 13                           NaN                            Thirteen Colonies
 14                           NaN                                        Italy
 15                           NaN                            Thirteen Colonies
 16                           NaN                                North America
 17                           NaN                                North America
 18                           NaN                   North America, West Indies
 19                           NaN  North America, present-day Pittsburgh area.
 20                      > 50,000                                       Russia
 21                           NaN                    Pacific Northwest natives
 22                           NaN                                North America
 23                   > 2,000,000                                       Persia
 24                           NaN                                      England
 25                           NaN                                        Spain
 26                           NaN                               Plains Indians
 27                           NaN                               Pueblo Indians
 28                           NaN                                United States
 29                           NaN                   New South Wales, Australia
 30                           NaN                                United States
 31                           NaN                                United States

          Date                                       Event  \
 0   1702–1703                                         NaN
 1   1707–1709                     Great Smallpox Epidemic
 2   1710–1712          Great Northern War plague outbreak
 3   1713–1715                                         NaN
 4   1714–1715                                         NaN
 5   1720–1722                   Great Plague of Marseille
 6   1721–1722                                         NaN
 7        1729                                         NaN
 8        1730                                         NaN
 9   1732–1733                                         NaN
 10       1733                                         NaN
 11       1738                        Great Plague of 1738
 12       1738                                         NaN
 13  1739–1740                                         NaN
 14       1743                                         NaN
 15       1747                                         NaN
 16  1755–1756                                         NaN
 17       1759                                         NaN
 18       1761                                         NaN
 19       1763                                         NaN
 20  1770–1772                 Russian plague of 1770–1772
 21      1770s                                         NaN
 22       1772                                         NaN
 23       1772                          1772 Persia plague
 24  1775–1776                                         NaN
 25       1778                                         NaN
 26  1780–1782            North American smallpox epidemic
 27       1788                                         NaN
 28       1788                                         NaN
 29  1789–1790                                         NaN
 30       1793                                         NaN
 31  1793–1798  Yellow Fever Epidemic of 1793, resurgences

                           Disease  Ref.
 0                        Smallpox  [38]
 1                        Smallpox   NaN
 2                          Plague   NaN
 3                         Measles  [39]
 4                         Measles  [40]
 5                          Plague  [41]
 6                        Smallpox  [42]
 7                         Measles  [43]
 8                    Yellow fever   NaN
 9                       Influenza  [44]
 10                       Smallpox  [45]
 11                         Plague   NaN
 12                       Smallpox  [46]
 13                        Measles   NaN
 14                         Plague  [47]
 15                        Measles   NaN
 16                       Smallpox   NaN
 17                        Measles  [48]
 18                      Influenza   NaN
 19                       Smallpox  [49]
 20                         Plague   NaN
 21                       Smallpox  [50]
 22                        Measles   NaN
 23                         Plague   [8]
 24                      Influenza  [51]
 25                   Dengue fever  [52]
 26                       Smallpox  [53]
 27                       Smallpox  [54]
 28                        Measles   NaN
 29                       Smallpox  [55]
 30  Influenza and Epidemic Typhus   NaN
 31                   Yellow fever  [56]  ,
    Death toll (estimate)               Location       Date  \
 0                    NaN                  Spain  1800–1803
 1                    NaN  Ottoman Empire, Egypt       1801
 2                    NaN          United States       1803
 3                    NaN                  Egypt       1812
 4                    NaN         Ottoman Empire       1812
 ..                   ...                    ...        ...
 56                   NaN                  Egypt       1881
 57               > 9,000         India, Germany  1881–1896
 58                  3164               Montreal       1885
 59               1000000              Worldwide  1889–1890
 60                   NaN            West Africa       1900

                      Event         Disease      Ref.
 0                      NaN    Yellow fever      [57]
 1                      NaN  Bubonic plague      [58]
 2                      NaN    Yellow fever       NaN
 3                      NaN          Plague       NaN
 4                      NaN          Plague      [59]
 ..                     ...             ...       ...
 56                     NaN         Cholera  [65][66]
 57  Fifth cholera pandemic         Cholera      [60]
 58                     NaN        Smallpox  timeline
 59  1889–1890 flu pandemic       Influenza      [83]
 60                     NaN    Yellow fever       NaN

 [61 rows x 6 columns],
    Death toll (estimate)                             Location          Date  \
 0                    NaN                          Congo Basin     1896–1906
 1              > 800,000                 Europe, Asia, Africa     1899–1923
 2                    113                        San Francisco     1900–1904
 3                    NaN                               Uganda     1900–1920
 4                    NaN                                Egypt          1902
 5                     22                                India          1903
 6                      4                            Fremantle          1903
 7                  40000                                China     1910–1912
 8            1.5 million                            worldwide     1915–1926
 9      up to 100,000,000                            worldwide     1918–1920
 10                   NaN                               Russia     1918–1922
 11                    30                          Los Angeles          1924
 12                    43                          Croydon, UK          1937
 13                   NaN                                Egypt     1942–1944
 14                   NaN                                China          1946
 15                   NaN                                Egypt          1946
 16                   NaN                                Egypt          1947
 17               2000000                            worldwide     1957–1958
 18                   NaN                            worldwide     1961–1975
 19                     4                               Sweden          1963
 20               1000000                            worldwide     1968–1969
 21                     5                          Netherlands          1971
 22                    35                           Yugoslavia          1972
 23                   NaN                        United States     1972–1973
 24                 15000                                India          1974
 25          > 32,000,000  worldwide(commenced in Congo Basin)  1960–present
 26                   NaN                        South America         1990s
 27                    52                                India          1994
 28                   231                            worldwide     1996–2001
 29                   NaN                          West Africa          1996
 30                   105                             Malaysia     1998–1999
 31                   NaN                      Central America          2000

                                          Event                      Disease  \
 0                                          NaN              Trypanosomiasis
 1                       Sixth cholera pandemic                      Cholera
 2                                          NaN               Bubonic plague
 3                                          NaN              Trypanosomiasis
 4                                          NaN                      Cholera
 5                                          NaN               Bubonic Plague
 6                                          NaN               Bubonic plague
 7                            1910 China plague               Bubonic plague
 8        1915 Encephalitis lethargica pandemic      Encephalitis lethargica
 9                                  Spanish flu  Influenza Spanish Flu Virus
 10                                         NaN                       Typhus
 11  1924 Los Angeles pneumonic plague outbreak             Pneumonic plague

In [15]:
epidemic_df = pd.DataFrame(tables)
epidemic_df

,0
0,...
1,Death toll (estima...
2,Death toll (estimate) \ 0...
3,Death toll (estimate) ...
4,Death toll (estimate) Locatio...
5,Death toll (estimate) ...
6,Death toll (estimate) ...
7,vteDi...
8,...
9,vteNatural disasters · list by death toll ...
10,0 ...
11,0 ...
12,0 ...
13,0 ...
14,0 ...
15,vteHistory of medicine...
16,vtePublic health ...
17,0 ...

In [18]:
epidemic_df = pd.DataFrame(tables[0])
#epidemic_df.columns = ['Death toll (estimate)', 'Location', 'Date', 'Event','Disease','Ref.']
epidemic_df.head()

,0,1
0,Plague panel with the triumph of death. 1607–3...,Plague panel with the triumph of death. 1607–3...
1,Duration,Human history